name = "DoubleArrayTries"
uuid = "abbaa0e5-f788-499c-92af-c35ff4258c82"
authors = ["chengchingwen <adgjl5645@hotmail.com> and contributors"]
version = "0.0.2"

[deps]
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StringViews = "354b36f9-a18e-4713-926e-db85100087ba"

[compat]
OffsetArrays = "1.12"
StringViews = "1"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
